packages/next-drupal/src/get-access-token.ts, packages/next-drupal/src/get-menu.ts, packages/next-drupal/src/get-paths.ts, packages/next-drupal/src/get-resource-collection.ts, packages/next-drupal/src/get-resource-type.ts, packages/next-drupal/src/get-resource.ts, packages/next-drupal/src/get-view.ts, packages/next-drupal/src/types.ts, packages/next-drupal/src/utils.ts
First of all, awesome work! I'm also using Drupal and Next.js and this module looks really great. 
I'm currently working on a Next.js app with personalized content. I use a different oauth strategy to obtain an access token. I would like te be able to use my own access token in the requests to the json api.
=> Make access token configurable

modules/next/composer.json
Removed patch for drupal/subrequests "Subrequest failed validation" because it is fixed in subrequests module.
=> Removed patch for drupal/subrequests

www/docs/authentication/password-grant.mdx
I was going through the authentication example and found that the npm package is named jwt-decode not jwt_decode. Trying to install jwt_decode will result in an error.
After that everything is working.
=> Fix wrong package name in password-grant.mdx

modules/next/src/Routing/NextSiteHtmlRouteProvider.php, modules/next/tests/src/Kernel/Controller/NextSiteEntityControllerTest.php
The environment variables page does not show config overridden via settings.php even though this config is used in the controller.
This is useful for multi-env setups where for example the base URL might differ (local, staging, prod) or if you don't want your preview secret in config.
=> fix(next): show overridden config on environment variables page

modules/next/modules/next_extras/next_extras.module, modules/next/modules/next_extras/next_extras.services.yml, modules/next/modules/next_extras/src/NextCacheInvalidator.php
Moves the code invoked in `hook_entity_update` in next_extras to a service. Also adds a method to invalidate a path directly. This is useful if you are defining a page in Next.js that has data fetching methods without being tied to an entity.
=> feat(next): next cache invalidator service

packages/next-drupal/src/get-menu.ts
This fixes an issue where a menu might be empty. We want to return an empty array that can be serialized via props.
=> fix(next-drupal): handle cases where menu might be empty

modules/next/next.services.yml
Improve the way the `main_content_renderer.html` service is defined by decorating the base one instead of replacing it entirely.
=> #131 Make the main_content_renderer a service

packages/next-drupal/src/client.ts, packages/next-drupal/src/types.ts
This PR introduces a `throwJsonApiErrors` client options.
- When set to true, `throwJsonApiErrors` will throw errors which are shown in the Next.js overlay.
- This is set to true by default in non-production environments.
- In production, all errors are logged to the console and never thrown.
```ts
const drupal = new DrupalClient("https://example.com", {
throwJsonApiErrors: false,
})
```
=> feat(next-drupal): introduce throwJsonApiErrors option

www/content/tutorials/quick-start/install-drupal.mdx
I ended up running into issue #275 trying to follow along with the [Quick Start guide](https://next-drupal.org/learn/quick-start). This is because the instructions there didn't specify that Standard is required, and what I *actually* wanted to do was install Umami instead.
@shadcn got me sorted lickety-split (thank you!) BUT how about let's improve the docs here so the next person who tries this doesn't hit the same problem. :)
=> [docs] Note that "Standard" profile should be selected, add pointer to Umami demo

examples/example-blog/components/meta.tsx, examples/example-marketing/components/meta.tsx, examples/example-umami/components/meta.tsx
This will fix the following warning:
> Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
This is caused by subtle differences between how React renders elements and nodes.
=> fix: Warning title element received an array with more than 1 element

modules/next/modules/next_jsonapi/src/Controller/EntityResource.php, modules/next/modules/next_jsonapi/tests/src/Kernel/Controller/EntityResourceTest.php
Allows the max size to be set via `page[limit]` even when using `path` in sparse fieldset.
=> feat(next): allow max size to be set via page limit

modules/next/modules/next_jsonapi/src/Controller/EntityResource.php, modules/next/modules/next_jsonapi/tests/src/Kernel/Controller/EntityResourceTest.php
Follow up from #333 we should treat `next_jsonapi.size_max` as a hard limit.
=> fix(next): size_max should be a hard limit

.github/workflows/next-drupal.yml
This PR switches the `next-drupal` workflow to using `pull_request_target`. 
For added security we now require all PRs from outside collaborators to be approved.
=> ci: switch to pull_request_target

modules/next/modules/next_jsonapi/src/Controller/EntityResource.php
From https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpFoundation/CHANGELOG.md#60
> Retrieving non-scalar values using InputBag::get() will throw BadRequestException (use InputBad::all() instead to retrieve an array)
Fixes #403
=> fix(next): switch from InputBag::get to InputBag::all

modules/next/tests/src/Kernel/Plugin/PathRevalidatorTest.php
Fixes https://www.drupal.org/project/next/issues/3329383
=> fix(next): add ProphecyTrait to PathRevalidatorTest

modules/next/src/Event/EntityActionEvent.php
I was facing the same issue as described in: https://github.com/chapter-three/next-drupal/issues/421
After some debugging I figured out that the `$entity->toUrl()->toString()` in `modules/next/src/Event/EntityActionEvent.php::createFromEntity` was causing the early rendering when trying to authorize with Authorization Code grant type.
For more info see: https://www.lullabot.com/articles/early-rendering-a-lesson-in-debugging-drupal-8
=> Add cacheability metadata from the entity url

.commitlintrc.json, .husky/commit-msg, CONTRIBUTING.md, package.json, yarn.lock
Fixes #536 and adds documentation for how we prefer to have git commit messages formatted.
=> Fix commitlint integration and add semantic commit message docs

.github/workflows/next.yml
=> ci(next): fix Drupal version constraints in Composer commands

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml
Update the GitHub issue templates to add a "not package-specific" option to the dropdown. This is helpful for issues related to CI or repo-wide tasks.
=> chore: update GitHub issue templates' package chooser

packages/next-drupal-query/.npmignore
GitHub Issue: #556
The NPM package has the src/ and tests/ files included and they are just bloat when downloading the package from npmjs.org.
Fixes #556
=> build: remove unnecessary files from NPM package

package.json, packages/next-drupal-query/package.json, packages/next-drupal/package.json, yarn.lock
GitHub Issue: #528 
This PR upgrade to latest `microbundle` release. And then removes UMD and legacy-ESM builds.
This PR depends on the #561 and includes that commit.
=> Deprecate project builds except modern ES Modules, CommonJS and Types

package.json
The `test:next` script failed due to incorrect configuration path, and missing SIMPLETEST_DB environment variable. This runs the Drupal PHPUnit tests in memory with SQLite.
This fixes that path and sets the environment variable.
=> chore: fix test:next

modules/next/src/Form/NextSiteForm.php
fixes #614
GitHub Issue: #614
Uses the `url` form element for URL validation when creating or editing Next.js sites.
=> fix(next): url form element for Next.js site form

.github/workflows/next.yml, modules/next/tests/src/Kernel/Plugin/PathRevalidatorTest.php
GitHub Issue: #547 
* Adds Drupal 10.1 to the GitHub test suite. 
* I've also removed Drupal 9.5 since it is EOL. https://www.drupal.org/about/announcements/blog/drupal-9-is-end-of-life
* PHP 8.0 is not supported by any version of Drupal 10, so it's been removed as well. https://www.drupal.org/docs/getting-started/system-requirements/php-requirements
* A comment in #547 [explains the GuzzleHttp Response additions that fixed a failing test](https://github.com/chapter-three/next-drupal/issues/547#issuecomment-1852673680)
=> ci(next): add Drupal 10.1 to CI test matrix

.github/workflows/next.yml, modules/next/modules/next_jsonapi/tests/src/Kernel/Controller/EntityResourceTest.php
GitHub Issue: #542
Runs the `next` module tests against Drupal 10.2.0-rc1
=> ci(next): add Drupal 10.2 to CI test matrix

.github/workflows/next.yml, modules/next/.gitlab-ci.yml
GitHub Issue: #542
Now that Drupal 10.2.0 has been released, this PR removes the `@RC` tag from the Drupal 10.2.x entry in the CI workflow.
=> Update CI to Drupal 10.2.0

MAINTAINING.md, lerna.json
Add docs so we don't accidentally publish an alpha release as the `latest` release like I just had Rob do. (oops.)
This also removes `next-drupal-query` from Lerna config.
=> Add dist-tag info to maintaining docs

packages/next-drupal/src/client.ts, packages/next-drupal/src/logger.ts, packages/next-drupal/src/utils.ts, packages/next-drupal/tests/client.test.ts
GitHub Issue: #668
In the `DrupalClient`, this changes the internal `_debug()` method to a public `debug()` method. It also changes a previously public `debug` property (boolean) to an internal property.
This PR also fixes some code formatting in the first commit.
=> Add public debug() method to DrupalClient

modules/next/modules/next_jsonapi/src/Controller/EntityResource.php
GitHub Issue: #527
I've had an issue where we could not build more than 1000 pages in a sitemap in nextjs because we could not paginate JSON:API beyond that point. This seems to be because of this issue.
=> #527 - Ensure offset is respected in JSON:API.

.github/workflows/next-drupal.yml, examples/example-blog/components/meta.tsx, examples/example-graphql/pages/[...slug].tsx, examples/example-marketing/components/meta.tsx, examples/example-umami/components/meta.tsx
GitHub Issue: #700
Runs tests across entire monorepo instead of just in packages/next-drupal and modules/next
=> ci(next-drupal): run code formatting/linting on full monorepo

modules/next/composer.json
GitHub Issue: #704 
_Please add a link to the GitHub issue
where this problem is discussed._
Allow "cweagans/composer-patches" both versions i.e. 1.x and 2.x.
=> Allow 1.x and 2.x of "cweagans/composer-patches".

examples/example-graphql/pages/api/revalidate.ts, examples/example-marketing/pages/api/revalidate.ts, examples/example-router-migration/app/[...slug]/page.tsx, examples/example-router-migration/app/api/revalidate/route.ts, modules/next/modules/next_extras/src/NextCacheInvalidator.php, modules/next/modules/next_jwt/src/Plugin/Next/PreviewUrlGenerator/Jwt.php, modules/next/src/Entity/NextSite.php, modules/next/src/Plugin/Next/PreviewUrlGenerator/SimpleOauth.php, modules/next/tests/src/Kernel/Entity/NextSiteTest.php, modules/next/tests/src/Kernel/Plugin/PathRevalidatorTest.php, modules/next/tests/src/Kernel/Plugin/SimpleOauthPreviewUrlGeneratorTest.php, modules/next/tests/src/Kernel/Renderer/MainContent/HtmlRendererTest.php, packages/next-drupal/src/client.ts, packages/next-drupal/src/deprecated/preview.ts, packages/next-drupal/src/draft.ts, packages/next-drupal/tests/DrupalClient/basic-methods.test.ts, packages/next-drupal/tests/DrupalClient/pages-router-methods.test.ts, packages/next-drupal/tests/__mocks__/next.ts, packages/next-drupal/tests/draft/draft.test.ts, starters/basic-starter/pages/api/revalidate.ts, starters/graphql-starter/pages/api/revalidate.ts
GitHub Issue: #718
Replaces "slug" with "path" in revalidate/preview/draft URLs.
=> Replace "slug" with "path" in draft/revalidate URLs

.github/workflows/next-drupal.yml, .nvmrc
GitHub Issue: #740
A change has been introduced into Node.js v18.20 and v20.10 and later that affects how Jest is able to use v8 for code coverage. Using an older version of node.js will allow the code coverage report to be reported correctly _consistently_.
=> Work-around for flakey code coverage reporting

packages/next-drupal/src/deprecated/translate-path.ts, packages/next-drupal/src/next-drupal.ts, packages/next-drupal/tests/NextDrupal/resource-methods.test.ts, packages/next-drupal/tests/NextDrupalBase/basic-methods.test.ts, packages/next-drupal/tests/NextDrupalPages/pages-router-methods.test.ts, packages/next-drupal/tests/utils/mocks/data.ts, packages/next-drupal/tests/utils/mocks/fetch.ts
GitHub Issue: #687 
`translatePath()` and `getResourceByPath()` return `null` when the given path is not found. NextDrupal incorrectly returns `null` for ALL errors, not just 404 errors.
This PR throws any error that is not a 404 error and continues to return null for 404 errors.
=> throw non-404 errors from /router/translate-path responses

examples/example-auth/package.json, examples/example-blog/package.json, examples/example-client/package.json, examples/example-custom-auth/package.json, examples/example-custom-cache/package.json, examples/example-custom-fetcher/package.json, examples/example-custom-serializer/package.json, examples/example-graphql/package.json, examples/example-marketing/package.json, examples/example-router-migration/package.json, examples/example-search-api/package.json, examples/example-umami/package.json, examples/example-webform/package.json, starters/basic-starter/package.json, starters/graphql-starter/package.json, starters/pages-starter/package.json
This PR:
* tags all three of the starters as `2.0.0-beta.0`
* upgrades the `examples` and `starters` to use `next-drupal@^2.0.0-beta.0`
=> Update starters/examples to beta release

www/components/card.tsx, www/components/layout.tsx, www/components/pager.tsx, www/components/sidebar-nav.tsx, www/pages/blog/index.tsx, www/pages/guides/index.tsx, www/pages/index.tsx, www/pages/learn/[...slug].tsx, www/pages/learn/index.tsx
Fixes #781
GitHub Issue: #781 
Ran the new-link codemod to automatically upgrade previous versions of Next.js to the new <Link> usage.
=> docs(www): run codemod to resolve Invalid `<Link>` with `<a>` child

.github/workflows/next.yml, modules/next/.gitlab-ci.yml, modules/next/composer.json, modules/next/modules/next_extras/next_extras.info.yml, modules/next/modules/next_extras/src/NextCacheInvalidator.php, modules/next/modules/next_graphql/next_graphql.info.yml, modules/next/modules/next_jsonapi/next_jsonapi.info.yml, modules/next/modules/next_jsonapi/src/NextJsonapiServiceProvider.php, modules/next/modules/next_jsonapi/tests/src/Kernel/Controller/EntityResourceTest.php, modules/next/modules/next_jwt/next_jwt.info.yml, modules/next/modules/next_jwt/src/EventSubscriber/JwtEventSubscriber.php, modules/next/next.info.yml, modules/next/next.services.yml, modules/next/src/EventSubscriber/EntityActionEventRevalidateSubscriber.php, modules/next/src/Form/NextSettingsForm.php, modules/next/src/NextSettingsManager.php, modules/next/src/Plugin/Next/Revalidator/Path.php, modules/next/src/Plugin/Next/SitePreviewer/Iframe.php, modules/next/tests/modules/next_tests/next_tests.info.yml, modules/next/tests/modules/next_tests/src/EventSubscriber/EntityActionEventSubscriber.php, modules/next/tests/modules/next_tests/src/EventSubscriber/EntityRevalidatedEventSubscriber.php, modules/next/tests/src/Kernel/Event/EntityActionEventTest.php, modules/next/tests/src/Kernel/Event/EntityRevalidatedEventTest.php, modules/next/tests/src/Kernel/NextSettingsManagerTest.php, modules/next/tests/src/Kernel/Plugin/SimpleOauthPreviewUrlGeneratorTest.php
GitHub Issue: #
_Please add a link to the GitHub issue: https://github.com/chapter-three/next-drupal/issues/777
where this problem is discussed._
Getting ready for this 
A clear and concise description of what the request is.
If applicable, add screenshots to help explain your issue.
=> Adding D11 support for nextjs.

modules/next/modules/next_jsonapi/tests/src/Kernel/Controller/EntityResourceTest.php, modules/next/tests/src/Kernel/Controller/NextPreviewUrlControllerTest.php, modules/next/tests/src/Kernel/Entity/NextEntityTypeConfigTest.php, modules/next/tests/src/Kernel/Entity/NextSiteTest.php, modules/next/tests/src/Kernel/Event/EntityActionEventTest.php, modules/next/tests/src/Kernel/Event/EntityRevalidatedEventTest.php, modules/next/tests/src/Kernel/NextEntityTypeManagerTest.php, modules/next/tests/src/Kernel/NextSettingsManagerTest.php, modules/next/tests/src/Kernel/Plugin/PathRevalidatorTest.php, modules/next/tests/src/Kernel/Plugin/SimpleOauthPreviewUrlGeneratorTest.php, modules/next/tests/src/Kernel/Plugin/SiteResolverTest.php, modules/next/tests/src/Kernel/Renderer/MainContent/HtmlRendererTest.php
GitHub Issue: #
_Please add a link to the GitHub issue
where this problem is discussed._
Tests no longer install sequences table. This is deprecated in Drupal 11 and was adding noise to module tests.
* see the following change record for more information: https://www.drupal.org/node/3349345
=> fix: remove Drupal 11 deprecations from module tests

turbo.json, www/components/video.tsx, www/pages/blog/[...slug].tsx, www/pages/docs/[[...slug]].tsx, www/pages/guides/[...slug].tsx, www/pages/index.tsx, www/pages/learn/[...slug].tsx
- [ x ] Other (docs)
GitHub Issue: #
_Please add a link to the GitHub issue
where this problem is discussed._
* Removed a deprecated property from turborepo config.
* Resolved type errors that appeared to be side effects from package updates.
=> fix: resolve docs build failures on app router branch

www/content/tutorials/graphql/apply-patches.mdx, www/content/tutorials/quick-start/apply-patches.mdx
This PR updates the apply patches entries in the documentation. The patches were no longer applying, and the subrequests patch should no longer be needed.
=> fix: update apply patches documentation

starters/basic-starter/app/[...slug]/page.tsx, starters/basic-starter/app/page.tsx
Fixes #808
Experimenting with Copilot Workspace here...
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/chapter-three/next-drupal/pull/816?shareId=689c7fd0-59ef-4fae-a2af-59f43f67bca3).
=> Add cache options to getResource/getResourceCollection calls in basic starter page templates

starters/basic-starter/app/api/revalidate/route.ts, starters/graphql-starter/app/api/revalidate/route.ts
Fixes: #807 
Adds tag revalidation to the API route (api/revalidate/route.ts) in the Basic starter and the GraphQL starter.
=> Add tag revalidation to basic-starter and graphql-starter

packages/next-drupal/src/next-drupal.ts, packages/next-drupal/src/types/options.ts, packages/next-drupal/tests/NextDrupal/resource-methods.test.ts, packages/next-drupal/tests/NextDrupalBase/fetch-methods.test.ts, starters/basic-starter/app/[...slug]/page.tsx
Fixes #809
Add support for the `cache` option in the Next Drupal client.
* Add `cache` option to `JsonApiWithNextFetchOptions` type in `packages/next-drupal/src/types/options.ts`.
* Update `fetch` method in `packages/next-drupal/src/next-drupal.ts` to pass the `cache` option as part of the `init` object if provided.
* Add tests for the `cache` option in `fetch` and `getResource` methods in `packages/next-drupal/tests/NextDrupalBase/fetch-methods.test.ts` and `packages/next-drupal/tests/NextDrupal/resource-methods.test.ts`.
* Adds cache option to getResource calls in basic starter.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/chapter-three/next-drupal/pull/817?shareId=6743112f-ce2b-4832-aba8-2c502aecda8f).
=> feat: add cache option to fetch

.gitignore
- [X ] Other
Ignored /local-next-drupal - this is a work in progress local environment. Want to ensure that git working area is clean for package publishing.
=> fix: ignore local environment

starters/basic-starter/app/[...slug]/page.tsx
This pull request includes a change to the `NodePageProps` type in the `starters/basic-starter/app/[...slug]/page.tsx` file. The change modifies the type of the `params` property from `NodePageParams` to `Promise<NodePageParams>`.
* `starters/basic-starter/app/[...slug]/page.tsx`: Changed the `params` property type in `NodePageProps` from `NodePageParams` to `Promise<NodePageParams>`. ([starters/basic-starter/app/[...slug]/page.tsxL62-R62](diffhunk://#diff-40e122ab26eb8d0eb598cfda52d4793bfc59b7472cb095e260a6dbc397b70089L62-R62))
This was causing a build error in the current canary starter.
=> fix: resolve type error in app router slug template

starters/basic-starter/lib/drupal.ts, starters/pages-starter/lib/drupal.ts
- [ x] `starters/basic-starter`
- [ x] `starters/pages-starter`
This pull request includes changes to the Drupal client configuration in two files to disable authentication by commenting out the related code blocks. This simplifies the setup for environments where authentication is not required. It also aligns better with our quick start docs which do not address authentication until the draft mode section of the quick start.
Changes to client configuration:
* [`starters/basic-starter/lib/drupal.ts`](diffhunk://#diff-49a273955f5a02b5f382c8f98eb155514b58d03ab3903215e3c6c3b00ebd862aL8-R12): Commented out the `auth` configuration block to disable authentication.
* [`starters/pages-starter/lib/drupal.ts`](diffhunk://#diff-7f59e64cf0146b99567636f542b …
=> fix: make authentication optional in basic and pages starters

www/config/site.ts, www/content/docs/authentication.mdx, www/content/docs/cache.mdx, www/content/docs/creating-resources.mdx, www/content/docs/deleting-resources.mdx, www/content/docs/fetching-resources.mdx, www/content/docs/index.mdx, www/content/docs/typescript.mdx, www/content/docs/updating-resources.mdx, www/content/guides/umami-demo.mdx, www/content/tutorials/draft-mode/create-oauth-client.mdx, www/content/tutorials/graphql/apply-patches.mdx, www/content/tutorials/graphql/configure-authentication.mdx, www/content/tutorials/graphql/enable-modules.mdx, www/content/tutorials/quick-start/apply-patches.mdx, www/next-env.d.ts, www/next.config.js
- [ X] Other
Final docs tweaks ahead of 2.x stable launch.
=> docs: Final 2.0 Docs Updates

scripts/sync-repo.sh
- [ x] Other
This pull request includes a small change to the `scripts/sync-repo.sh` file. The change removes the `--depth 1` option from the `git clone` command to ensure that the full history is cloned rather than just the latest commit.
* [`scripts/sync-repo.sh`](diffhunk://#diff-2568406177f99891dd19cc5114ec3d7adb1a230bc85ea945973cade26ffc5269L28-R28): Removed `--depth 1` from the `git clone` command to clone the full repository history.
=> build: fix bug in starter sync script that was preventing stable release publishing
